name: universal_realism_art
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  pull_to_refresh: ^2.0.0

  # state_managers/di/storages
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  bloc: ^8.1.2 
  get_it: ^7.6.7
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0

  #app bl
  pdf: ^3.10.7
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  go_router: ^13.1.0
  either_dart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

