name: wttr_in_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.8
  coverage: ^1.1.0
  flutter_lints: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  mocktail: ^0.3.0
  test: ^1.19.2
dependencies: {freezed_annotation: ^2.4.4, http: ^0.13.4, json_annotation: ^4.9.0}
