name: optimal_prime
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



 
  # settings
  path_provider: ^2.1.5
  battery_plus: ^6.2.0
  universal_ble: ^0.13.0
  background_fetch: ^1.3.7
  shared_preferences: ^2.3.3
  
  # nav
  go_router: ^14.6.1

  # ui
  flutter_svg: ^2.0.16
  lottie: ^3.1.3


  # utils
  logger: ^2.4.0

  # state BL
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5


  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
