name: freezed_weather
description: A rewrite of Flutter Weather Tutorial using freezed code generation.
publish_to: 'none' 
version: 2.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  weather_repository: 
    path: packages/weather_repository
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  google_fonts: ^4.0.4
  path_provider: ^2.0.10
  bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.4
  test: ^1.21.1

flutter:
  uses-material-design: true
